language: python
os:
- linux
services:
- docker
python:
- '3.6'
install:
- pip install .
- pip install pytest
script: pytest
deploy:
  provider: pypi
  user: magland
  on:
    tags: true
  password:
    secure: 3qE7y0kfmsfLRhhRCS4b7uiN0hoGKin2ILTQMjMzFr80YD5Qd7csxZktPVwNGsHhSs4U3Hx4fGGTVy3W4imZ9ZKwmXA6dVqvVsYhbjFlV2syIH9DHG26/F5a0CiQwV7lt4dIzKtzFYgO49EGSVTfURUTRb4aNJqtHlvRMZxOYiqoaUA+YeHGIsGCk6+hadJ9mq/MD4fSkqKCMJKv1MaRTCbLNnflrKDAwWVH2DSg7vDH6cTYQ2Nispbiu/5G6Eq5ZwIrla/YHtD7YnzCpQgbKjzAGDcA2XB0QEQ84CXs65+j7SRXfoZUVCza8YwqqZpJINUUSD1eEjH3LAn3KmKi+YonU0+qJj28GShpC9GDeyP2Il2OE6sYeI0A6WcqNHVfMNTz/ML7gUX/f7WLZ26/7oVv+d8zeZOMnFmZj2MRJXB1dlQOuuETxPZg3kAHfAn9FsdvglWL4SoWG7C5DLgACYuKUKQPFSzvqlc9/n4JT+1HN9sfTMSkvijmSweCE9Hx38fS2Rj/6j0U1rxdzKTiEEKU4DQd7kspVq2fkJr2FNtwkvuCch/vbG4aZtqeqYBNlethWUMXcOXIk/h7EAQd5uTqX9OPSGP/qrOjS9/I31SPcF6BApopKQPbTc/3bTZVeFsQWWSLfBJBHAhqF5WH8cT3dTO76ztVXKMINZG50HE=
